config/routes.rb
Rails.application.routes.draw do
  resources :beers do
      collection { post :import }
  end

  devise_for :users
  get 'deletebeer' => 'beers#deleteindex'
  get 'takeonedown/:id' => 'beers#take_one_down', as: 'takeonedown'
  root 'beers#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
    belongs_to :user
    
    def self.search(query)
        query = query.downcase
        where("lower(name) like :q or lower(brewery) like :q or lower(beertype) like :q", q: "%#{query}%")
    end    
    
    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
            row = Hash[[header, spreadsheet.row(i)].transpose]
            beer = find_by_name(row['name']) || new
            beer.attributes = row.to_hash
            beer.save!
        end
    end
  
    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
          when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
          when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
          when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
          when "gdoc" then Roo::Google.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    has_many :beers, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy, :take_one_down]

  respond_to :html

  def index
    if current_user
      @breweries = Beer.select(:brewery).distinct.where('user_id = ?', current_user.id).order(:brewery)
      if params[:search]
        @beers = Beer.search(params[:search])
        @beers = @beers.where("user_id = ?", current_user.id).order(:brewery, :name)
      elsif params[:filter]
          @beers = Beer.search(params[:filter])
          @beers = @beers.where("user_id = ?", current_user.id).order(:brewery, :name)
      else
        @beers = Beer.where("user_id = ?", current_user.id).all.order(:brewery, :name)
      end
    respond_with(@beers)
    end
  end
    
  def deleteindex
      @beers = Beer.where("user_id = ?", current_user.id).all.order(:brewery, :name)
      @beers = @beers.contains(params[:contains]) if params[:contains].present?
      respond_with(@beers)
  end

  def show
    respond_with(@beer)
  end

  def new
    @beer = Beer.new
    respond_with(@beer)
  end

  def edit
  end

  def create
    @beer = Beer.new(beer_params)
    @beer.user_id = current_user.id
    @beer.brewery = @beer.brewery.titleize
    @beer.name = @beer.name.titleize
    @beer.save
    redirect_to beers_path
  end

  def update
    @beer.update(beer_params)
    redirect_to beers_path
  end
    
  def take_one_down
    if @beer.quantity > 0
        @beer.quantity -= 1
        @beer.save
        redirect_to beers_path
    else
        redirect_to beers_path, alert: "You're already out of this beer"
    end
  end

  def destroy
    @beer.destroy
    respond_with(@beer)
  end
    
  def import
    Beer.import(params[:file])
	redirect_to beers_path, notice: "Import submitted"
  end
    
  private
    def set_beer
      @beer = Beer.find(params[:id])
    end

    def beer_params
      params.require(:beer).permit(:user_id, :name, :brewery, :enjoydate, :expirationdate, :size, :quantity, :beertype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<div class='form-bkg'>
     <%= form_for(@beer) do |f| %>
      <% if @beer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

          <ul>
          <% @beer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
            <%= f.label :brewery %>
            <%= f.text_field :brewery, autocomplete: "on", required: true, class: 'form-control', placeholder: 'Name of the brewery' %>
      </div>
      <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', required: true, placeholder: 'Name of the beer' %>
      </div>
      <div class="form-group">
            <%= f.label :beertype %>
            <%= f.text_field :beertype, class: 'form-control', required: true, placeholder: 'Type of beer' %>
      </div>
      <div class="form-group">
            <%= f.label 'Enjoy After Date' %>
            <%= f.date_field :enjoydate, class: 'form-control' %>
      </div>
        <div class="form-group">
            <%= f.label 'Expiration Date' %>
            <%= f.date_field :expirationdate, class: 'form-control' %>
      </div>
      <div class="form-group">
            <%= f.label :size %>
            <%= f.select :size, options_for_select([["12","12"],["22","22"],["25","25"]]), {},{class: 'form-control', placeholder: 'Size of the bottle'} %>
      </div>
      <div class="form-group">
            <%= f.label :quantity %>
            <%= f.text_field :quantity, class: 'form-control', required: true, placeholder: 'How many do you have?' %>
      </div>
      <div class="actions">
        <%= f.submit "Submit", class: 'btn btn-primary' %>
      </div>
    <% end %>
    <br>
    <%= link_to 'Back', beers_path %>
</div>

app/views/beers/deleteindex.html.erb
<h1 class='page-title'>Delete a beer</h1>

<% if user_signed_in? %>
    <% @beers.each do |beer| %>
        <%= link_to beer, method: :delete, data: {confirm: 'Are you sure?'}, class: 'no-underline' do %>
            <div class='delete-beer-item'>
                <h3><%= beer.brewery.titleize + " " + beer.name.titleize %></h3>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/beers/edit.html.erb
<h1 class='page-title'>Change it up</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<% if user_signed_in? %>
    <h1 class='page-title'>Your cellar</h1>
    <%= form_tag beers_path, :method => 'get' do %>
        <p class="search">
            <%= text_field_tag :search, params[:search], placeholder: "Search brewery, beer name, or type" %>
            <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
        </p>
    <% end %>
            
    <%= form_tag beers_path, :method => 'get' do %>        
        <p class="filter">
           <%= collection_select :beer, 'filter', @breweries, :brewery, :brewery, {prompt: "Filter by brewery"}, {:name => 'filter'} %>
        <%= link_to 'Clear Filter', root_path, class: 'clear-filter' %>
        </p>
    <% end %>
   
    <% if @beers.empty? %>
        <h2 class="page-title">You don't have any beers yet,<br><%= link_to 'add some now!', new_beer_path %></h2>
    <% else %>
        <% @beers.each do |beer| %>
            <div class='beer-item'>
                <h3><%= beer.brewery.titleize + ' ' + beer.name.titleize %></h3>
                <a data-toggle="collapse" href="#collapse<%= beer.id %>">Click For Details</a><br>
                <ul id="collapse<%= beer.id %>" class="collapse">
                    <li><%= beer.beertype %></li>
                    <li><b><%= "#{beer.quantity} left" %></b></li>
                    <li><%= "Size: #{beer.size} oz." %></li>
                    <li><%= "Enjoy after #{beer.enjoydate}" %></li>
                    <li><%= "Expires #{beer.expirationdate}" %></li>
                    <li>Added <%= l beer.created_at, format: :long %></li>
                    <li><%= link_to 'Edit', edit_beer_path(beer) %></li>
                </ul>
                <%= link_to 'Take One Down', takeonedown_path(beer), data: {confirm: 'Subtract one of this beer from your inventory?'}, class: 'btn btn-danger btnDown' %>
            </div>
        <% end %>
    <% end %>
<% else %>
    <p class="intro">Have a large collection of craft beer in your cellar?<br>Keep track of your inventory here!</p>
<% end %>
<br>

app/views/beers/new.html.erb
<h1 class="page-title">New beer</h1>

<%= render 'form' %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery %>
</p>

<p>
  <strong>Brewyear:</strong>
  <%= @beer.brewyear %>
</p>

<p>
  <strong>Size:</strong>
  <%= @beer.size %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @beer.quantity %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/_footer.html.erb
<footer>
    <h1>This is the footer</h1>
</footer>

app/views/layouts/_header.html.erb
<header class="clearfix">
    <%= image_tag 'brewcellarlogo.png', class: 'logo', alt: 'Brew Cellar Logo' %>
    <div class='brand'>
        <h1>BrewCellar</h1>
    </div>
</header>

app/views/layouts/_mainnav.html.erb
<nav id="main-nav" class='main-nav'>
    <ul>
        <% if current_user %>
            <li><%= link_to 'Cellar', beers_path, class: 'btnIndex menu-btn' %></li>
            <li><%= link_to 'Add', new_beer_path, class: 'btnAdd menu-btn' %></li>
            <li><%= link_to 'Delete', deletebeer_path, class: 'btnDelete menu-btn'%> </li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'btnLogout menu-btn' %> </li>
        <% else %>
            <li class='loggedOut'><%= link_to 'Sign In', new_user_session_path, class: 'btnLogin menu-btn' %>
            <li class='loggedOut'><%= link_to 'Sign Up', new_user_registration_path, class: 'btnLogin menu-btn' %>
        <% end %>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brew Cellar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag %>
</head>
<body>
    <%= render "layouts/header" %>
    <main>
        <%= render "layouts/mainnav" %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="container">
            <%= yield %>
        </div>
    </main>
</body>
</html>